# Excel spreadsheet to JSON conversion, generated by Grok June 22, 2025.
# Question groupings are in each Excel tab.  
import pandas as pd
import os

path = '/Users/Oliver/Library/Mobile Documents/com~apple~CloudDocs/Documents - Mac/AI/Virtual-Legacy/Virtual-Legacy-MVP-1/Questions/'
excel_file = path + '2025-06-22 Questions for Virtual Legacy.xlsx'
output_dir = path

os.makedirs(output_dir, exist_ok=True)

excel_data = pd.ExcelFile(excel_file)

for sheet_name in excel_data.sheet_names:
    df = pd.read_excel(excel_file, sheet_name=sheet_name)
    
    # Validate id column
    if 'questionId' not in df.columns:
        raise ValueError(f"No 'id' column in sheet '{sheet_name}'")
    
    # Auto-generate IDs only for null values
    if df['questionId'].isnull().any():
        null_mask = df['questionId'].isnull()
        max_id = df['questionId'].dropna().max() if not df['questionId'].dropna().empty else 0
        df.loc[null_mask, 'questionId'] = range(int(max_id) + 1, int(max_id) + 1 + null_mask.sum())
    
    # Check for duplicates after ID generation
    if df['questionId'].duplicated().any():
        raise ValueError(f"Duplicate IDs in sheet '{sheet_name}'")
    
    # Fill empty cells
    df = df.fillna('')
    
    # Convert to JSON
    json_path = f'{output_dir}/{sheet_name}.json'
    df.to_json(json_path, orient='records', lines=False, indent=4, force_ascii=False)
    
    print(f"Converted sheet '{sheet_name}' to {json_path}")